---
- hosts: kubeadm
  become: true

  tasks:
    - name: close fireware          
      command: '{{ item }}'
      with_items:
        - systemctl stop firewalld
        - systemctl disable firewalld
        
    - name: disabled SELINUX 
      selinux: state=disabled
    
    - name: close SeLinux
      lineinfile: 
        dest: /etc/selinux/config 
        regexp: ^SELINUX= 
        line: "SELINUX=disabled"
        
    - lineinfile: 
        dest: /etc/selinux/config 
        regexp: ^net.ipv4.ip_forward.* 
        line: "net.ipv4.ip_forward=1"
    - lineinfile: 
        dest: /etc/selinux/config 
        regexp: ^net.bridge.bridge-nf-call-ip6tables.* 
        line: "net.bridge.bridge-nf-call-ip6tables=1"
    - lineinfile: 
        dest: /etc/selinux/config 
        regexp: ^net.bridge.bridge-nf-call-iptables.* 
        line: "net.bridge.bridge-nf-call-iptables=1"
    - lineinfile: 
        dest: /etc/selinux/config 
        regexp: ^net.ipv6.conf.all.disable_ipv6.* 
        line: "net.ipv6.conf.all.disable_ipv6=1"
    - lineinfile: 
        dest: /etc/selinux/config 
        regexp: ^net.ipv6.conf.default.disable_ipv6.* 
        line: "net.ipv6.conf.default.disable_ipv6=1"
    - lineinfile: 
        dest: /etc/selinux/config 
        regexp: ^net.ipv6.conf.lo.disable_ipv6.* 
        line: "net.ipv6.conf.lo.disable_ipv6=1"
    - lineinfile: 
        dest: /etc/selinux/config 
        regexp: ^net.ipv6.conf.all.forwarding.* 
        line: "net.ipv6.conf.all.forwarding=1"
        

    - lineinfile:
        dest: /etc/sysctl.conf
        line: "{{ item }}"
      with_items: 
        - 'net.ipv4.ip_forward = 1'
        - 'net.bridge.bridge-nf-call-ip6tables = 1'
        - 'net.bridge.bridge-nf-call-iptables = 1'
        - 'net.ipv6.conf.all.disable_ipv6 = 1'
        - 'net.ipv6.conf.default.disable_ipv6 = 1'
        - 'net.ipv6.conf.lo.disable_ipv6 = 1'
        - 'net.ipv6.conf.all.forwarding = 1'
        - 'net.ipv4.ip_forward = 1'
      
    - name: sysctl -p
      command: 'sysctl -p'
      
    - name: remove kube old version           
      yum:
        name:
          - kubelet   
          - kubeadm 
          - kubectl 
        state: absent 
        
    - name: Kubernetes Repo
      yum_repository:
        name: Kubernetes
        description: Kubernetes
        enabled: yes
        baseurl: http://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64
        gpgcheck: no
        gpgkey: http://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg
        
    - name: install kube           
      yum:
        name:
          - kubelet-{{version}}   
          - kubeadm-{{version}}
          - kubectl-{{version}}
        state: present 
        
    - lineinfile: 
        dest: /usr/lib/systemd/system/docker.service
        regexp: ^ExecStart=/usr/bin/dockerd.* 
        line: "ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd"
        
    - name: start docker0          
      command: '{{ item }}'
      with_items:
        - systemctl daemon-reload
        - systemctl restart docker
        - systemctl enable kubelet
        - systemctl start kubelet